export const API_CONSTANTS = {
  SCRAPER_SERVICE_BASE_URL: process.env.SCRAPER_SERVICE_BASE_URL || 'http://localhost:3000',
  DEFAULT_TIMEOUT: 10000,
  RETRY_ATTEMPTS: 3,
};

export const HISTORY_CONSTANTS = {
  MAX_SESSION_ITEMS: 100,
  SESSION_EXPIRY_HOURS: 24,
};
